name: DemoCD

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o ${{ github.workspace }}/demo 
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ${{ github.workspace }}//demo
      
  deploy-dev:
     runs-on: ubuntu-latest
     environment:
       name: dev
       url: ${{ steps.app-web.outputs.webapp-url }}
     needs: build
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: ${{ github.workspace }}//demo
        
       - name: 'Run Azure webapp deploy action using publish profile credentials'
         uses: azure/webapps-deploy@v2
         id: app-web
         with: 
           app-name: ${{ secrets.AZURE_WEBAPP_NAME }} 
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }} 
           package: '${{ github.workspace }}//demo'
           slot-name: 'dev'
     

  deploy-qa:
     runs-on: ubuntu-latest
     environment:
       name: qa
       url: ${{ steps.app-web.outputs.webapp-url }}
     needs: build
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: ${{ github.workspace }}//demo
        
       - name: 'Run Azure webapp deploy action using publish profile credentials'
         uses: azure/webapps-deploy@v2
         id: app-web
         with: 
           app-name: ${{ secrets.AZURE_WEBAPP_NAME }} 
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }} 
           package: '${{ github.workspace }}//demo'
           slot-name: 'qa'
  
  deploy-prd2:
     runs-on: ubuntu-latest
     environment:
       name: prd2
       url: ${{ steps.app-web.outputs.webapp-url }}
     needs: deploy-qa
     steps:
       - uses: actions/download-artifact@v2
         with:
           name: artifact
           path: ${{ github.workspace }}//demo
        
       - name: 'Run Azure webapp deploy action using publish profile credentials'
         uses: azure/webapps-deploy@v2
         id: app-web
         with: 
           app-name: ${{ secrets.AZURE_WEBAPP_NAME }} 
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRD }} 
           package: '${{ github.workspace }}//demo'
           
     
